version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm test  # Run your tests here
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
